"type: feature 🔨": ["*/feature/*", "feat/*", "feature/*"]
"type: bug 🐛": ["*/bug/*", "fix/*", "bugfix/*", "bug/*"]
"type: chore 🧺": ["*/chore/*", "chore/*"]
"type: documentation ✏️": ["*/chore/docs*", "docs/*"]
