name-template: "v$RESOLVED_VERSION"

tag-template: "release-v$RESOLVED_VERSION"

template: |
  $CHANGES

version-resolver:
  major:
    labels:
      - "type: breaking"

  minor:
    labels:
      - "type: feature 🔨"
      - "type: feature"

  patch:
    labels:
      - "type: bug 🐛"
      - "type: chore 🧺"
      - "type: bug"
      - "type: chore"

categories:
  - title: Breaking
    labels:
      - "type: breaking"

  - title: New
    labels:
      - "type: feature 🔨"
      - "type: feature"

  - title: Bug Fixes
    labels:
      - "type: bug 🐛"
      - "type: bug"

  - title: Maintenance
    labels:
      - "type: chore 🧺"
      - "type: chore"

  - title: Documentation
    labels:
      - "type: documentation ✏️"
      - "type: documentation"
