name: pm / pull request

on:
  pull_request:
    types: [opened]

env:
  PROJECT_BOARD: "TakeShape"
  ICEBOX_COLUMN_NAME: "Icebox"
  STARTED_COLUMN_NAME: "In Progress"
  BEFORE_REVIEW_COLUMN_NAME: "Waiting on Review"

jobs:
  assign-author:
    name: assign author
    runs-on: ubuntu-latest
    if: github.event.action == 'opened'
    steps:
      - name: assigning author to pr
        uses: technote-space/assign-author@v1

  pr-labeler:
    name: pr labeler
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    steps:
      - name: labeling pr
        uses: TimonVS/pr-labeler-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  clubhouse-link:
    name: clubhouse link
    if: github.event.action == 'opened' && startsWith(github.head_ref, 'ch')
    runs-on: ubuntu-latest
    steps:
      - name: extract id
        id: extract-id
        run: |
          if [[ $GITHUB_HEAD_REF =~ ^ch([0-9]+) ]]; \
          then \
            echo "::set-output name=clubhouse-id::${BASH_REMATCH[1]}"; \
          fi

      - name: get story name
        id: get-story-name
        env:
          CLUBHOUSE_API_KEY: ${{ secrets.CLUBHOUSE_API_KEY }}
          CLUBHOUSE_STORY_ID: ${{ steps.extract-id.outputs.clubhouse-id }}
        run: |
          story_name=$(curl -X GET \
            -H "Content-Type: application/json" \
            -H "Clubhouse-Token: ${CLUBHOUSE_API_KEY}" \
            -L "https://api.clubhouse.io/api/v3/stories/${CLUBHOUSE_STORY_ID}" | \
            jq -r ".name")
          echo "::set-output name=story-name::${story_name}";

      - name: add pr link in comment
        if: steps.get-story-name.outputs.story-name != ''
        uses: mshick/add-pr-comment@master
        with:
          message: |
            ## Related Clubhouse Story
            [${{ steps.get-story-name.outputs.story-name }}](https://app.clubhouse.io/takeshape/story/${{ steps.extract-id.outputs.clubhouse-id }})
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]"